#!/usr/bin/env bash
# Transfer a file from a client to a server
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i -o "$1" "$3"@"$2" "$4":~/
fi
