#!/usr/bin/env bash
# Configure Nginx so that 404 page contains a certain string
apt-get -y update
apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sed -ie "s/^server {$/location {\n\t;/g" /etc/nginx/sites-available/default
service nginx restart