#!/usr/bin/env bash
# Configure Nginx so that 404 page contains a certain string
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' | sudo tee /var/www/html/index.html
sed -ie "s/^server {$/server {\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/g" /etc/nginx/sites-available/default
service nginx restart