#!/bin/bash
.TH man(2) "10 December 1945" "eniac man page"
.SH NAME
eniac \- create a new LDAP user 
.SH SYNOPSIS
eniac
.SH DESCRIPTION
Eniac was Turing-complete, and able to solve "a large class of numerical problems" through reprogramming. 
.SH OPTIONS
eniac does not take any options.
.SH SEE ALSO
ENIAC could be programmed to perform complex sequences of operations(2), including loops(2), branches(2), and subroutines(2).
.SH BUGS
No known bugs.
.SH AUTHOR
University of Pennsylvania.
