#!/usr/bin/env bash
# config nginx to listen on port 80
apt-get -y update
apt-get -y install nginx
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
