#!/usr/bin/env bash
# this script manages programs running in the background (daemons)
test -f /var/run/my_process.pid
case "$1" in
    start)
	/manage_my_process
	/var/run/my_process.pid
        echo -n "manage_my_process started"
	;;

    stop)
	kill manage_my_process
	/usr/bin/rm -f /var/run/my_process.pid
	echo -n "manage_my_process stopped"
	;;

    restart)
	kill manage_my_process
	/usr/bin/rm -f /var/run/my_process.pid
	/manage_my_process
	/var/run/my_process.pid
	echo -n "manage_my_process restarted"
	;;

    *)
        echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
