#!/usr/bin/env bash
# this script manages programs running in the background (daemons)
test -f /var/run/my_process.pid
case "$i" in
    start)
        echo "manage_my_process started"
	/var/run/my_process.pid
	;;

    stop)
        echo "manage_my_process stopped"
	/usr/bin/rm -f /var/run/my_process.pid
	;;

    restart)
        echo "manage_my_process restarted"
	/usr/bin/rm -f /var/run/my_process.pid
	/var/run/my_process.pid
	;;

    *)
        echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
