#!/usr/bin/env bash
# this script manages programs running in the background (daemons)
test -f /manage_my_process
case "$1" in
    start)
	sudo ./manage_my_process
	pgrep ./manage_my_process | grep sudo | cut -f > /var/run/my_process.pid
        echo "manage_my_process started"
	;;

    stop)
	pkill -f ./manage_my_process
	/usr/bin/rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;

    restart)
	pkill -f ./manage_my_process
	/usr/bin/rm -f /var/run/my_process.pid
	sudo ./manage_my_process
	pgrep ./manage_my_process | grep sudo | cut -f > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;

    *)
        echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
