#!/usr/bin/env bash
# configure nginx to run as nginx user (not root)
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 0700 /etc/nginx/nginx.conf
sudo sed -i "s/^server {/a\nlisten 8080 default_server;\n" /etc/nginx/sites-available/default
service nginx restart
