#!/usr/bin/env bash
# configure nginx to run as nginx user (not root)
chown nginx:nginx /etc/nginx/nginx.conf
chmod 0700 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -f apache2
sudo -u nginx service nginx restart
